site_name: PyTrader Documentation
site_description: Web based trading app
site_author: James Shull
site_url: https://example.com
site_dir: docs_site


# Repository
repo_name: PyTrader
repo_url: https://github.com/example/PyTrader

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - API Documentation:
    - Authentication: api/authentication.md
    - Endpoints: api/endpoints.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
  - About: about.md

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]